### ISSUE TITLE
Dies when I try....

### ISSUE THREAD

**Issue by Guscoan** [webscraperio/image-downloader#4]
It just dies when i run it. My file is 3million lines long and 300mb? Was hoping it would work.... Any ideas
screenshot here... just dies... https://imgur.com/V6XFGmA

**Comment by lake15** [comment]
I have the same issue, however, my csv file is only about 150 rows.

**Comment by zernonia** [comment]
@Guscoan  @lake15   try to use cmd to run the command rather than drop the csv file onto the py file.

open cmd, navigate to the folder,eg: cd Desktop\\{folder location with your csv file}
then use this command : python image-downloader.py {your csv file}
