### ISSUE TITLE
renaming files trough web-scraper-order column

### ISSUE THREAD

**Issue by paddy95** [webscraperio/image-downloader#6]
Hi there,

First of all thank you very much for this script. I really did helped me with my job.
However currently I'm having troubles to rename files through "web-scraper-order" column. If I put there instead of default (f.e.: 1608498486-1648) data desired future file name (f.e.: 3245/285/330) script can't proceed and download the images. Apparently it has something to do with UTF-8 coding and slash - "/".
Can anybody give me an advice how to adjust the script so I can do such thing?

Any advice would be appreciated!

**Comment by kristapsws** [comment]
"/" can't be used in filenames because it is used to separate directories in file path. Try using different format for your filenames e.g. 3245-285-330 or 3245|285|330.
